In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
x = np.arange(1, 25).reshape(12, 2)
y = np.array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [3]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [8]:
x_train

array([[ 1,  2],
       [13, 14],
       [23, 24],
       [ 9, 10],
       [11, 12],
       [ 3,  4],
       [ 7,  8],
       [ 5,  6],
       [19, 20]])

In [9]:
x_test

array([[21, 22],
       [15, 16],
       [17, 18]])

In [10]:
y_train

array([0, 0, 0, 1, 0, 1, 0, 1, 0])

In [11]:
y_test

array([1, 1, 1])

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=4, random_state=4)

In [13]:
x_train

array([[17, 18],
       [ 5,  6],
       [23, 24],
       [ 1,  2],
       [ 3,  4],
       [11, 12],
       [15, 16],
       [21, 22]])

In [14]:
x_test

array([[ 7,  8],
       [ 9, 10],
       [13, 14],
       [19, 20]])

In [15]:
y_train

array([1, 1, 0, 0, 1, 0, 1, 1])

In [16]:
y_test

array([0, 1, 0, 0])

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=4, random_state=4, stratify=y)

In [18]:
x_train

array([[21, 22],
       [ 1,  2],
       [15, 16],
       [13, 14],
       [17, 18],
       [19, 20],
       [23, 24],
       [ 3,  4]])

In [19]:
x_test

array([[11, 12],
       [ 7,  8],
       [ 5,  6],
       [ 9, 10]])

In [20]:
y_train

array([1, 0, 1, 0, 1, 0, 0, 1])

In [21]:
y_test

array([0, 0, 1, 1])

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, shuffle=False)

In [23]:
x_train

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [24]:
x_test

array([[17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [25]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [26]:
x = np.arange(20).reshape(-1, 1)
y = np.array([5, 12, 11, 19, 30, 29, 23, 40, 51, 54, 74, 62, 68, 73, 89, 84, 89, 101, 99, 106])
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [27]:
y

array([  5,  12,  11,  19,  30,  29,  23,  40,  51,  54,  74,  62,  68,
        73,  89,  84,  89, 101,  99, 106])

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=8, random_state=0)

In [29]:
model = LinearRegression().fit(x_train, y_train)
model.intercept_

3.1617195496417523

In [30]:
model.coef_

array([5.53121801])

In [31]:
model.score(x_train, y_train)

0.9868175024574796

In [32]:
model.score(x_test, y_test)

0.9465896927715023

In [33]:
y_pred=model.predict(x_test)

In [34]:
y_pred

array([102.72364381,   8.69293756, 108.25486182,  47.41146366,
        58.47389969,  97.19242579,  36.34902764,  75.06755374])

In [35]:
y_test

array([ 99,  12, 106,  51,  74, 101,  23,  73])

In [36]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
x, y = load_boston(return_X_y=True)

In [37]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=0)

In [38]:
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(x_train, y_train)
model.score(x_train, y_train)

0.7668160223286262

In [39]:
model.score(x_test, y_test)

0.6882607142538016

In [40]:
y_pred = model.predict(x_test)

In [41]:
y_pred

array([24.58155243, 24.51629253, 29.71379915, 12.51132696, 21.34965428,
       19.05443022, 20.94614567, 20.95753329, 19.54644456, 20.53025981,
        6.96153725, 17.1707288 , 16.85608802,  5.74921859, 40.74378524,
       32.62964196, 22.88997064, 37.11387241, 30.94054261, 23.12796161,
       24.54411122, 25.50446659, 20.37697803, 30.82455449, 22.42949559,
       12.45993818, 17.10212725, 18.52819406, 34.91024736, 20.63587192,
       18.38567423, 17.65503994, 19.39633993, 23.8814007 , 29.06559846,
       19.49721361, 10.81151906, 25.66712254, 18.47597465, 15.40207099,
       26.55714333, 20.56301083, 21.8661955 , 16.10102382, 22.05244625,
       24.87100697, 19.97650209, 22.98518884,  9.46781454, 23.96350651,
       21.66355147, 16.95911711, 24.48952338, 28.692406  , 13.80788563,
       21.35149553, 20.72525415, 14.54282452, 16.61385208, 22.02338757,
       17.15670419, 21.27690041, 33.12409276, 31.40070549, 18.22591067,
       33.35335507, 18.26583607, 18.69440702, 19.46223051, 23.01

In [42]:
y_test

array([22.6, 50. , 23. ,  8.3, 21.2, 19.9, 20.6, 18.7, 16.1, 18.6,  8.8,
       17.2, 14.9, 10.5, 50. , 29. , 23. , 33.3, 29.4, 21. , 23.8, 19.1,
       20.4, 29.1, 19.3, 23.1, 19.6, 19.4, 38.7, 18.7, 14.6, 20. , 20.5,
       20.1, 23.6, 16.8,  5.6, 50. , 14.5, 13.3, 23.9, 20. , 19.8, 13.8,
       16.5, 21.6, 20.3, 17. , 11.8, 27.5, 15.6, 23.1, 24.3, 42.8, 15.6,
       21.7, 17.1, 17.2, 15. , 21.7, 18.6, 21. , 33.1, 31.5, 20.1, 29.8,
       15.2, 15. , 27.5, 22.6, 20. , 21.4, 23.5, 31.2, 23.7,  7.4, 48.3,
       24.4, 22.6, 18.3, 23.3, 17.1, 27.9, 44.8, 50. , 23. , 21.4, 10.2,
       23.3, 23.2, 18.9, 13.4, 21.9, 24.8, 11.9, 24.3, 13.8, 24.7, 14.1,
       18.7, 28.1, 19.8, 26.7, 21.7, 22. , 22.9, 10.4, 21.9, 20.6, 26.4,
       41.3, 17.2, 27.1, 20.4, 16.5, 24.4,  8.4, 23. ,  9.7, 50. , 30.5,
       12.3, 19.4, 21.2, 20.3, 18.8, 33.4, 18.5, 19.6, 33.2, 13.1,  7.5,
       13.6, 17.4,  8.4, 35.4, 24. , 13.4, 26.2,  7.2, 13.1, 24.5, 37.2,
       25. , 24.1, 16.6, 32.9, 36.2, 11. ,  7.2, 22

In [43]:
from sklearn.metrics import max_error
max_error(y_test,y_pred)

25.48370746890006

In [44]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6882607142538016

In [45]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

3.6331273740246237

In [46]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

25.790362150702467

In [47]:
from math import sqrt
sqrt(mean_squared_error(y_test,y_pred))

5.078421226198401

## Lab 17
1. WAP to perform Linear Regerssion on Diabetes Dataset and find the R sqaured score
2. WAP to perform Linear Regerssion on Diabetes Dataset and find the max error
3. WAP to perform Linear Regerssion on California Housing Dataset and find the RMSE, MAE and MSE

In [48]:
df = pd.read_csv("diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [59]:
X = (df.iloc[:, :-1])
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [62]:
Y = (df.iloc[:, -1:])
Y.head()

Outcome
0        1
1        0
2        1
3        0
4        1

In [66]:
X_train, Y_train, X_test, Y_test = train_test_split(X, Y, test_size=0.33, shuffle=False)

In [67]:
X_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [68]:
Y_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
514            3       99             54             19       86  25.6   
515            3      163             70             18      105  31.6   
516            9      145             88             34      165  30.3   
517            7      125             86              0        0  37.6   
518           13       76             60              0        0  32.8   

     DiabetesPedigreeFunction  Age  
514                     0.154   24  
515                     0.268   28  
516                     0.771   53  
517                     0.304   51  
518                     0.180   41

In [71]:
X_test.tail()

Outcome
509        0
510        1
511        0
512        0
513        0

In [72]:
Y_test.tail()

Outcome
763        0
764        0
765        0
766        1
767        0

In [80]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model = LogisticRegression()

In [81]:
model.fit(X_train, X_test)

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [82]:
pred = model.predict(Y_train)

In [83]:
accuracy_score(Y_test, pred)

0.8070866141732284

In [84]:
from sklearn.metrics import r2_score
r2_score(Y_test, pred)

0.12308884661452824

In [85]:
#WAP to perform Linear Regerssion on Diabetes Dataset and find the max error
from sklearn.metrics import max_error
max_error(Y_test, pred)

1

In [86]:
#WAP to perform Linear Regerssion on California Housing Dataset and find the RMSE, MAE and MSE
df2 = pd.read_csv("housing.csv")
df2.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [87]:
df2.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [88]:
df2["total_bedrooms"] = df2.fillna(df2.total_bedrooms.median())

In [89]:
df2.total_bedrooms.isnull().sum()

0

In [97]:
df3 = df2.drop('longitude', axis=1)

In [98]:
df3 = df3.drop('latitude', axis=1)

In [99]:
df3 = df3.drop('ocean_proximity', axis=1)

In [100]:
df3.head()

housing_median_age  total_rooms total_bedrooms  population  households  \
0                41.0        880.0        -122.23       322.0       126.0   
1                21.0       7099.0        -122.22      2401.0      1138.0   
2                52.0       1467.0        -122.24       496.0       177.0   
3                52.0       1274.0        -122.25       558.0       219.0   
4                52.0       1627.0        -122.25       565.0       259.0   

   median_income  median_house_value  
0         8.3252            452600.0  
1         8.3014            358500.0  
2         7.2574            352100.0  
3         5.6431            341300.0  
4         3.8462            342200.0

In [101]:
X2 = df3.iloc[:, :-1]
Y2 = df3.iloc[:, -1:]

In [102]:
X2.head()

housing_median_age  total_rooms total_bedrooms  population  households  \
0                41.0        880.0        -122.23       322.0       126.0   
1                21.0       7099.0        -122.22      2401.0      1138.0   
2                52.0       1467.0        -122.24       496.0       177.0   
3                52.0       1274.0        -122.25       558.0       219.0   
4                52.0       1627.0        -122.25       565.0       259.0   

   median_income  
0         8.3252  
1         8.3014  
2         7.2574  
3         5.6431  
4         3.8462

In [103]:
Y2.head()

median_house_value
0            452600.0
1            358500.0
2            352100.0
3            341300.0
4            342200.0

In [104]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, shuffle=False)

In [106]:
model2 = LogisticRegression().fit(X_train, Y_train)

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [107]:
pred2 = model2.predict(X_test)

In [109]:
accuracy_score(Y_test, pred2)

0.8070866141732284

In [110]:
#R Squared score
r2_score(Y_test, pred2)

0.12308884661452824

In [111]:
#Mean Absolute Error
from sklearn.metrics import mean_absolute_error
mean_absolute_error(Y_test, pred2)

0.19291338582677164

In [ ]:
#Mean Squared error
from sklearn.metrics import mean_squared_error
mean_squared_error(Y_test,y_pred)